### ISSUE TITLE
为什么一直报error？

### ISSUE THREAD

**Issue by zuichu35** [halfzm/ProPainter-Webui#1]
server disconneted without sending a response

**Comment by halfzm** [comment]
详细报错信息发出来

**Comment by zuichu35** [comment]
server disconneted without sending a response.就是右上角报这个错，是直接下载你的压缩包，解压，然后打开bat，进入webui。环境是rtx3060笔记本。

**Comment by halfzm** [comment]
详细报错信息是命令行窗口中的信息，仅仅给我这一句话我没法儿解答。你可以先去搜一下我的B站视频/专栏，里面涵盖了大部分报错的处理情况。
