### ISSUE TITLE
NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by lucasmen9527** [halfzm/ProPainter-Webui#3]
去水印的时候，报错：
Traceback (most recent call last):
  File "D:\soft\watermark_remover\ProPainter\inference_propainter.py", line 273, in <module>
    frames, flow_masks, masks_dilated = frames.to(device), flow_masks.to(device), masks_dilated.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.63 GiB (GPU 0; 11.99 GiB total capacity; 6.48 GiB already allocated; 0 bytes free; 6.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

<img width="1488" alt="image" src="https://github.com/halfzm/ProPainter-Webui/assets/64875226/56492bb4-fd0d-4ea5-b252-37977c25bb9a">

**Comment by halfzm** [comment]
显存不足
